version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile-nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - node-network
   

networks:
  node-network:
    driver: bridge
